name: CheckStyle

on:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-jre-alpine
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run checkstyle
        run: java -jar .github/workflows/checkstyle-10.21.2-all.jar -c .github/workflows/google_checks.xml .
        
